### PR TITLE
Flush store cache in operational order

### LINKED ISSUE #1610: Solution for Cockroach FK not support deferrable
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [ ] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [ ] Are you reporting to the correct repository?
* [ ] Did you search for an existing issue or pull request?

### Description

Due to cockroach db not support FK constraint set to be deferrable https://github.com/cockroachdb/cockroach/issues/31632 , we need to support cache flush entity with orders.

Propose : We can add an `operationIndex` to each records, then we extract records from each entity sort them with `operationIndex`

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

### PR DESCRIPTION
**Pull request by jiqiang90**
# Description

- enable with `store-flush-in-order` flag
- only work with **non-historica**l project, as historical projects has no constraints between entity, we can always use bulk method.
-  it will only sort **relational** model 's record, other non-relational model can be flush with bulk method.
-  We need to flush all records instead of flush the the latest records from model's record only, as record and its fk record could be missing during flush in operational order.

Tests:

- working with both postgres and cockroach db,  worker and non-workers

Fixes #1610

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] I have tested locally
- [x] I have performed a self review of my changes
- [ ] Updated any relevant documentation
- [x] Linked to any relevant issues
- [x] I have added tests relevant to my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] My code is up to date with the base branch

### CODE REVIEW

File: packages/node/src/yargs.ts [hunk 1]
```diff
@@ -201,6 +201,12 @@ export const yargsOptions = yargs(hideBin(process.argv))
         'If enabled writing data to the store is asynchronous with regards to block processing',
       type: 'boolean',
     },
+    'store-flush-in-order': {
+      demandOption: false,
+      describe:
+        'If enabled relational model will flush in original operational order, this only work in non-historical mode',
```
Comment (stwiname) [inline packages/node/src/yargs.ts:207]:
```suggestion
        'If enabled relational model will flush in original operational order, this only works in non-historical mode',
```

File: packages/node-core/src/indexer/storeCache/types.ts
Comment (stwiname) [inline packages/node-core/src/indexer/storeCache/types.ts:1]: It might be worth moving `SetValueModel` to its own file

File: packages/node-core/src/indexer/storeCache/storeCache.service.ts [hunk 2]
```diff
@@ -35,6 +37,24 @@ export class StoreCacheService implements BeforeApplicationShutdown {
   init(historical: boolean, useCockroachDb: boolean): void {
     this._useCockroachDb = useCockroachDb;
     this._historical = historical;
+    if (this.config.storeFlushInOrder) {
+      if (this._historical) {
+        logger.warn(`Flush store cache in order is not support with Historical feature,it will have no effect`);
```
Comment (stwiname) [inline packages/node-core/src/indexer/storeCache/storeCache.service.ts:42]:
```suggestion
        logger.warn(`Flush store cache in order is not supported with Historical feature, it will have no effect`);
```

File: packages/node-core/src/indexer/storeCache/storeCache.service.ts [hunk 3]
```diff
@@ -35,6 +37,24 @@ export class StoreCacheService implements BeforeApplicationShutdown {
...
+      } else {
+        this._storeFlushInOrder = this.config.storeFlushInOrder;
+        this.resetStoreOperationIndex();
+        logger.info(`Store cache will flush in order`);
+      }
+    }
+  }
+
+  resetStoreOperationIndex(): void {
```
Comment (stwiname) [inline packages/node-core/src/indexer/storeCache/storeCache.service.ts:51]: Can be private

File: packages/node-core/src/indexer/storeCache/storeCache.service.ts [hunk 4]
```diff
@@ -83,9 +102,25 @@ export class StoreCacheService implements BeforeApplicationShutdown {
...
+    );
+    // Handle record in operation order
+    for (const record of sortedFlushableRecords) {
+      const model = this.sequelize.model(record.entity);
+      if (record.action === IndexedOperationActionType.Set) {
+        await model.upsert(record.data, {transaction: tx});
+      } else if (record.action === IndexedOperationActionType.Remove) {
+        await model.destroy({where: {id: record.data.id} as any, transaction: tx});
+      }
+    }
```
Comment (stwiname) [inline packages/node-core/src/indexer/storeCache/storeCache.service.ts:119]: I think we can simplify this if we add a method to cache model. Something like `flushOperation(index: number)` then the model can handle the specific store operation and dealing with the model since we already have an instance of it there. 

Then we can have a really simple loop:

```ts
for (const i = 0; i < this._storeOperationIndex; i++) {
    // Flush operation can be a no-op if it doesn't hatve that index
    await Promise.all(this.models.map(m => m.flushOperation(i)));
}
```

I think it will also mean we can drop `IndexedOperationActionType` as the cacheModel knows what type of operation it is.

`flushOperation` should also remove the item from the cache as it has now been flushed, we don't seem to be doing that currently

File: packages/node-core/src/indexer/storeCache/cacheModel.ts [hunk 5]
```diff
@@ -45,6 +54,14 @@ export class CachedModel<
       getCacheOptions.max = this.config.storeGetCacheSize;
     }
     this.getCache = new GetData<T>(getCacheOptions);
+    if (Object.keys(this.model.associations).length > 0) {
+      this.hasAssociations = true;
+    }
+  }
+
+  init(storeFlushInOrder = false, getNextStoreOperationIndex: () => number) {
```
Comment (stwiname) [inline packages/node-core/src/indexer/storeCache/cacheModel.ts:62]: I think we should always keep the operation index even if we don't flush in order. It will simplify the code and doesn't have much overhead.

File: packages/node-core/src/indexer/storeCache/cacheModel.ts [hunk 6]
```diff
@@ -45,6 +54,14 @@ export class CachedModel<
       getCacheOptions.max = this.config.storeGetCacheSize;
     }
     this.getCache = new GetData<T>(getCacheOptions);
+    if (Object.keys(this.model.associations).length > 0) {
```
Comment (stwiname) [inline packages/node-core/src/indexer/storeCache/cacheModel.ts:57]: Nice!

File: packages/node-core/src/indexer/storeCache/storeCache.service.ts [hunk 7]
```diff
@@ -95,15 +130,23 @@ export class StoreCacheService implements BeforeApplicationShutdown {
...
+      } else {
+        await Promise.all(updatableModels.map((model) => model.flush(tx, blockHeight)));
+      }
       await tx.commit();
     } catch (e) {
       logger.error(e, 'Database transaction failed');
       await tx.rollback();
       throw e;
     }
+    this.resetStoreOperationIndex();
```
Comment (stwiname) [inline packages/node-core/src/indexer/storeCache/storeCache.service.ts:149]: I don't think this will work. Remember that we take a snapshot (`updatableModels`) that we flush, so in the mean time items can still be added to the cache. That would mean that the storeOperationIndex could keep incrementing while we're flushing. 

We could store another number as to what index we have flushed up to.

I don't think we need to reset the index, its very unlikely there would be enough operations that we reach the limit of `number` and in that case we could just throw an error to restart the node and reset the index.

**Comment by jiqiang90** [comment]
I been done some performance test with two method: for loop with models, and aggregate operations then for loop.

Here is the result with 1461 record to flushes

- for loop with models (not reset op index):  5068ms
- for loop with models (reset op index):  1008ms
- aggregate operations: 2159ms


So we still need to reset op index to optimize performance.

**Comment by stwiname** [comment]
With this is the for loop starting from 0 or starting from the last flushed index?
>     * for loop with models (not reset op index):  5068ms

**Comment by jiqiang90** [comment]
> With this is the for loop starting from 0 or starting from the last flushed index?
> 
> > ```
> > * for loop with models (not reset op index):  5068ms
> > ```

Flush from 0.  I think rather than set to 0,  make sense to store the last flushed index, I will make a change

**Review by stwiname — APPROVED** [review]
