### PR TITLE
fix poi operationHash and miss poi blocks

### LINKED ISSUE #1903: Poi operationHash difference get from db and cache
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [ ] Did you search for an existing issue or pull request?

### Description

Poi operation hash is calculated from entity operation, entityType and data. 

However, we discovered when use get method, data could be inconsistent from cahce and fetched from db.

Example data from cache

```
data: {"id":"0x02","owner":"0x70d0AFeE4A6A314d71046DA9B4BbcFB8Fd1722Ce","metadata":"Qmcf1Yp3NeLkfM78KjcK4JKdtY7N2eMEodCFKd1ZyQUdAX","currentDeployment":"QmRRv6VS1bDdjpUu83NNfWsgw6qo89vRptmAPMPoZC8Xh1","currentVersion":"QmXSJwq6FUQsyJjGAQNqR9qgxQtj4ZSZfJ1yWhuo4ucXz3","updatedTimestamp":"2023-04-20T02:30:38.000Z","createdTimestamp":"2023-04-06T08:08:14.000Z","createdBlock":41204769,"__block_range":{"fn":"int8range","args":[41204769,null]},"lastEvent":"handleUpdateQueryDeployment:41730830"}

```

Example data from db 

```

data: {"id":"0x02","owner":"0x70d0AFeE4A6A314d71046DA9B4BbcFB8Fd1722Ce","metadata":"Qmcf1Yp3NeLkfM78KjcK4JKdtY7N2eMEodCFKd1ZyQUdAX","currentDeployment":"QmRRv6VS1bDdjpUu83NNfWsgw6qo89vRptmAPMPoZC8Xh1","currentVersion":"QmXSJwq6FUQsyJjGAQNqR9qgxQtj4ZSZfJ1yWhuo4ucXz3","updatedTimestamp":"2023-04-20T02:30:38.000Z","createdTimestamp":"2023-04-05T20:08:14.000Z","createdBlock":41204769,"lastEvent":"handleUpdateQueryDeployment:41730830"}

```

This is due to we had a hook on sequelize to exclude `__block_range`. But when data get from getCache, once data has been flushed, it has created __block_range in the object. 

To reproduce this, 

```ts

      testModel.set(
        'entity1_id_0x01',
        {
          id: 'entity1_id_0x01',
          field1: 1,
        },
        1
      );
      const entity1 = await testModel.get('entity1_id_0x01');

      await flush();

      // We can see entity2 has added __block_range from entity1
      const entity2 = await testModel.get('entity1_id_0x01');

```

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

### LINKED ISSUE #1908: Need Mutex for both get and flush within cache
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [ ] Did you search for an existing issue or pull request?

### Description

In recent debug for Poi, I noticed some poi blocks are missed from get method and mmr never been added.

I suspected this is due to we are missing Mutex lock in the get method, so during get (cache + read from db), there are nothing to stop cache start flushing, some data has missed during this time.

After I added lock for get method, this issue seems never happened again. 

We also need to create more tests for this to verify this hypothesis

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

### PR DESCRIPTION
**Pull request by jiqiang90**
# Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1908 , instead of merge with data, we use data from plainModel only.  see this test case here to reproduce the issue. 
Fixes #1903 

Also, because change of `getPoiBlocksByRange` we removed this feature here, this is to avoid we skipped sync poi blocks within the cache. This also reduce the code complexity https://github.com/subquery/subql/blob/f30ff52b9b1a1b64ea02903dca8b261b85a348e5/packages/node-core/src/indexer/mmr.service.ts#L161

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] I have tested locally
- [ ] I have performed a self review of my changes
- [ ] Updated any relevant documentation
- [ ] Linked to any relevant issues
- [ ] I have added tests relevant to my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] My code is up to date with the base branch
- [ ] I have updated relevant changelogs. [We suggest using chan](https://github.com/geut/chan/tree/main/packages/chan)

### CODE REVIEW

File: packages/node-core/src/indexer/storeCache/cachePoi.ts [hunk 1]
```diff
@@ -71,6 +71,13 @@ export class CachePoiModel implements ICachedModelControl, PoiInterface {
   }
 
   async getPoiBlocksByRange(startHeight: number): Promise<ProofOfIndex[]> {
+    await this.mutex.waitForUnlock();
+    const poiBlocks = await this.plainPoiModel.getPoiBlocksByRange(startHeight);
+    return poiBlocks.length !== 0 ? poiBlocks : [];
```
Comment (stwiname) [inline packages/node-core/src/indexer/storeCache/cachePoi.ts:76]: If the length is 0 wont poiBlocks == []
```suggestion
    return poiBlocks;
```

File: packages/node-core/src/indexer/mmr.service.ts [hunk 2]
```diff
@@ -131,50 +162,10 @@ export class MmrService extends baseMmrService implements OnApplicationShutdown
...
-              Math.max(1, Number(lastProcessedHeight) - this.nextMmrBlockHeight)
-            );
-          }
-          await this.addDefaultLeafWithRange(this.nextMmrBlockHeight, Number(lastProcessedHeight) + 1);
-        }
-        await delay(MMR_AWAIT_TIME);
+      if (this._syncPoiJob !== undefined) {
+        await this._syncPoiJob;
       }
+      this._syncPoiJob = this.syncPoiJob(logging);
```
Comment (stwiname) [inline packages/node-core/src/indexer/mmr.service.ts:168]: Whats the reason for keeping a global reference to this?

File: packages/node-core/src/indexer/mmr.service.ts [hunk 3]
```diff
@@ -107,6 +108,36 @@ export class MmrService extends baseMmrService implements OnApplicationShutdown
     this._poi = poi;
   }
 
+  async syncPoiJob(logging?: boolean): Promise<void> {
```
Comment (stwiname) [inline packages/node-core/src/indexer/mmr.service.ts:111]: Can be private

**Review by stwiname — APPROVED** [review]
Looks good. Do you think its time we had a standardised sequelize mock? We seem to have quite a few now and they are mostly the same
