### PR TITLE
fix index name too long issue

### LINKED ISSUE #1595: Re-create index due to table and field name too long
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [ ] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [ ] Are you reporting to the correct repository?
* [ ] Did you search for an existing issue or pull request?

### Description
```
ERROR: relation "share_staking_subscribes_owner_staking_subscribe_id__block_rang" already exists
```
Index on fk will recreate if the table and field name are too long. 

Examaple.

We use this sql to check whether index has been created. 

``` sql
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a, pg_namespace s WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'share_staking_subscribes' AND s.oid = t.relnamespace AND s.nspname = 'land-sale-subql' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;

```

From returned result, we notice missing `e` from word block_range, and this is due to index was created and name over postgres limit.

image

Once this index were no found due to incorrect index name, it will create this index again. 

For now, we can reduce the table and field name length. 

To fix this, we can use hashed name index. 

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

### PR DESCRIPTION
**Pull request by jiqiang90**
# Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1595 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] I have tested locally
- [x] I have performed a self review of my changes
- [ ] Updated any relevant documentation
- [x] Linked to any relevant issues
- [ ] I have added tests relevant to my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] My code is up to date with the base branch

### CODE REVIEW

File: packages/node-core/src/utils/sequelizeUtil.ts [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+    throw new Error(`Index on table ${tableName} has not fields:
+${NodeUtil.inspect(index)}`);
+  }
+
+  const fields = index.fields.map((field) => {
+    if (typeof field === 'string') {
+      return field;
+    }
+
+    if (field instanceof BaseSqlExpression) {
```
Comment (stwiname) [inline packages/node-core/src/utils/sequelizeUtil.ts:32]: Will this work if `BaseSqlExpression` is redefined?

Comment (jiqiang90) [reply packages/node-core/src/utils/sequelizeUtil.ts]: field will always be string in this case

**Review by stwiname — APPROVED** [review]
