### PR TITLE
Fix publish ipfs 503

### LINKED ISSUE #1262: Improve publish command fix IPFS 503 issue
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description

Subql publish command failed occasionally due to large amount of files to upload, and encountered 503 issue. 

When we publish project to IPFS, publish controller will loop each file in manifest and upload it. 
This causing an issue of repeat uploading. For example, project use evm processor with multiple datasource and shared same processor asset, this will require upload these assets files in multiple times.

We can improve this by provide extract upload files to a map, and reuse the IPFS address for the known/uploaded files, this will help resolve the publish failed issue.

### PR DESCRIPTION
**Pull request by bighammerw**
# Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1262 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I have tested locally

### CODE REVIEW

File: packages/cli/src/controller/publish-controller.ts [hunk 1]
```diff
@@ -115,16 +117,21 @@ export async function uploadFile(
   }
   let ipfsClusterCid: string;
   try {
-    ipfsClusterCid = await UploadFileByCluster(
-      determineStringOrFsStream(content) ? await fs.promises.readFile(content.path, 'utf8') : content,
-      authToken
-    );
+    if (fileMap.get(content)) {
```
Comment (stwiname) [inline packages/cli/src/controller/publish-controller.ts:120]:
```suggestion
    if (fileMap.has(content)) {
```

**Review by stwiname — COMMENTED** [review]
I can see how this improves efficiency by reusing CID of already uploaded files. 

How does it solve the 503 error though? Is it because of rate limiting?

**Comment by jiqiang90** [comment]
> I can see how this improves efficiency by reusing CID of already uploaded files. 
> 
> 
> 
> How does it solve the 503 error though? Is it because of rate limiting?

I assume by reduce repeat upload same file concurrently it should also reduce number of requests, so it will also reduce the chance hit the rate limit?

**Review by stwiname — APPROVED** [review]
