### PR TITLE
change createproject URL , project create issue, regx for project nam…

### LINKED ISSUE #1320: Validate project name when creating from the CLI
### Description

When creating a project from the CLI there is no validation or formatting, this could lead to broken projects and urls from the hosted service. 

We should format the project name used [here](https://github.com/subquery/subql/blob/main/packages/cli/src/controller/project-controller.ts#L14) with this logic:
```ts
export const suffixFormat = (value: string) => {
  return value
    .replace(/(^\s*)|(\s*$)/g, '')
    .replace(/\s+/g, '-')
    .toLowerCase();
}
```

There will be API changes to validate and enforce this

### PR DESCRIPTION
**Pull request by bighammerw**
…e and project key

# Description
update project command index issue 
create project with regx name
fix create project output URL

Fixes #1320 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I have tested locally
- [ ] I have performed a self review of my changes
- [ ] Linked to any relevant issues
- [ ] I have added tests relevant to my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] My code is up to date with the base branch

### CODE REVIEW

File: packages/cli/src/controller/project-controller.ts [hunk 1]
```diff
@@ -31,7 +38,7 @@ export async function createProject(
           apiVersion: `v${apiVersion}`,
           description: description,
           gitRepository: gitRepository,
-          key: `${organization}/${project_name}`,
+          key: `${organization}/${name}`,
```
Comment (jiqiang90) [inline packages/cli/src/controller/project-controller.ts:41]: ${organization}/${suffixFormat(project_name)}

Comment (bighammerw) [reply packages/cli/src/controller/project-controller.ts:41]: okk

**Review by jiqiang90 — APPROVED** [review]
