### PR TITLE
Fix for unstructured storage abis (codegen)

### LINKED ISSUE #1975: incorrect abi codegen `Initialize_string_string_string_address[]_Transaction`
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Description

When generating from abi that has inputs of non alphabetical (non structured contract abis)
e.g. `address[]`

this can be replicated using the abis from this contract
https://gnosisscan.io/address/0xa178b166bea52449d56895231bb1194f20c2f102#code

### Steps to Reproduce
https://github.com/subquery/subquery-example-gnosis-poap
`yarn`
`yarn codegen`
`yarn build`

build will fail due to incorrect abi codegen

### Any other information

Is there any other information you would like to add?

### PR DESCRIPTION
**Pull request by bz888**
# Description
Fixes #1975

Fix incorrect codegen on unstructured storage proxy contract abi

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] I have tested locally
- [x] I have performed a self review of my changes
- [ ] Updated any relevant documentation
- [x] Linked to any relevant issues
- [x] I have added tests relevant to my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] My code is up to date with the base branch
- [x] I have updated relevant changelogs. [We suggest using chan](https://github.com/geut/chan/tree/main/packages/chan)

### CODE REVIEW

File: packages/cli/src/controller/codegen-controller.ts [hunk 1]
```diff
@@ -306,9 +306,11 @@ export function processAbis(
   return renderInterfaceJobs;
 }
 
-function joinInputAbiName(abiObject: abiInterface) {
+export function joinInputAbiName(abiObject: abiInterface) {
   // example: "TextChanged_bytes32_string_string_string_Event", Event name/Function type name will be joined in ejs
-  const inputToSnake: string = abiObject.inputs.map((obj) => obj.type.toLowerCase()).join('_');
+  const inputToSnake = abiObject.inputs
+    .map((obj) => (obj.type.includes('[]') ? obj.type.replace(/\[\]/g, '_arr') : obj.type.toLowerCase()))
```
Comment (stwiname) [inline packages/cli/src/controller/codegen-controller.ts:312]: The includes check is redundant. If there's no match it wont replace and we should lowercase even if there's an `[]`

**Review by stwiname — APPROVED** [review]
