### PR TITLE
Substrate api throw with block height if failed fetch block

### LINKED ISSUE #469: api get block failed should print its block height

### PR DESCRIPTION
**Pull request by jiqiang90**
Closes #469

### CODE REVIEW

File: packages/node/src/utils/substrate.ts [hunk 1]
```diff
@@ -247,8 +250,12 @@ export async function fetchBlocksRange(
 ): Promise<SignedBlock[]> {
   return Promise.all(
     range(startHeight, endHeight + 1).map(async (height) => {
-      const blockHash = await api.rpc.chain.getBlockHash(height);
-      return api.rpc.chain.getBlock(blockHash);
+      try {
+        const blockHash = await api.rpc.chain.getBlockHash(height);
+        return api.rpc.chain.getBlock(blockHash);
+      } catch (err) {
+        logger.error(err, `failed to fetch block at height ${height}`);
```
Comment (stwiname) [inline packages/node/src/utils/substrate.ts:257]: I don't know the logger behaviour, but should the error be rethrown or does the logger rethrow?

Comment (jiqiang90) [reply packages/node/src/utils/substrate.ts:257]: Thanks, you are right, should be rethrown rather than just log it.

File: packages/node/src/utils/substrate.ts [hunk 2]
```diff
@@ -247,8 +247,12 @@ export async function fetchBlocksRange(
 ): Promise<SignedBlock[]> {
   return Promise.all(
     range(startHeight, endHeight + 1).map(async (height) => {
-      const blockHash = await api.rpc.chain.getBlockHash(height);
-      return api.rpc.chain.getBlock(blockHash);
+      try {
+        const blockHash = await api.rpc.chain.getBlockHash(height);
+        return await api.rpc.chain.getBlock(blockHash);
+      } catch (err) {
+        throw new Error(`failed to fetch block at height ${height}`);
```
Comment (ianhe8x) [inline packages/node/src/utils/substrate.ts:254]: the original error object should be re-thrown, not the one you created.

**Review by ianhe8x — CHANGES_REQUESTED** [review]

File: packages/node/src/utils/substrate.ts [hunk 3]
```diff
@@ -23,7 +23,9 @@ import {
 } from '@subql/types';
 import { last, merge, range } from 'lodash';
 import { BlockContent } from '../indexer/types';
+import { getLogger } from './logger';
 
+const logger = getLogger('substrate');
```
Comment (ianhe8x) [inline packages/node/src/utils/substrate.ts:28]: We never used `substrate` this category before, Don't think its good idea adding another.
Can you use the same log category as fetch service?

**Review by ianhe8x — CHANGES_REQUESTED** [review]

**Review by ianhe8x — APPROVED** [review]
