### PR TITLE
Proof of index (part 1)

### LINKED ISSUE #410: Proof of index
In the process of decentralized indexing, indexer strives to query data to obtain rewards, but it also faces the following challenges:

- Prove that the indexing of the block height has been completed
- It is also very difficult to trace the database operation of update/delete, we cannot know start from which block the indexer input incorrect data. 
- The current implementation cannot ensure the accuracy and reliability of the data.

Therefore,  we proposed a "proof of index" approach.  
(https://docs.google.com/drawings/d/1hYMt-IJDnvQFWR5iaLEMrgA9e4ksaKujZDbU7hnwZ7w/edit?usp=sharing). This method uses Merkle tree to manage the database operations in the current block of indexing, and generates a root hash, which is stored in block data. We regard the block as the leaf of the Merkle mountain range (https://github.com/mimblewimble/grin/blob/master/doc/mmr.md) , and continuously generate the MMR root and store with the block together.

- By comparing the indexer's MMR root value, we can quickly locate start from which block has a disagreement.
- According to the characteristics of the Merkel mountain range, we only need a small number of peak MMR root values to calculate the validity of a block data.
- By comparing the hashes of operations on the same block height, we can determine whether the same operation is performed by different indexers.

### PR DESCRIPTION
**Pull request by jiqiang90**
#410

### CODE REVIEW

File: packages/node/src/indexer/StoreOperations.ts [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+                dataBuffer,
+                Buffer.from(Buffer.from(fieldValue)),
+              );
+              break;
+            default:
+              //JSON
+              dataBuffer = u8aConcat(dataBuffer, Buffer.from(field.name));
+              dataBuffer = u8aConcat(
+                dataBuffer,
+                Buffer.from(JSON.stringify(fieldValue)),
```
Comment (ianhe8x) [inline packages/node/src/indexer/StoreOperations.ts:97]: probably we should check how sequalize handle js object, and we align our code with sequlize's

File: packages/node/src/indexer/entities/Poi.entity.ts [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+export function PoiFactory(sequelize: Sequelize, schema: string): PoiRepo {
+  return <PoiRepo>sequelize.define(
+    `_poi`,
+    {
+      id: {
+        type: DataTypes.INTEGER,
+        primaryKey: true,
+      },
+      chainBlockHash: {
+        type: DataTypes.STRING,
```
Comment (ianhe8x) [inline packages/node/src/indexer/entities/Poi.entity.ts:29]: DataTypes.BLOB

File: packages/node/src/indexer/StoreOperations.ts [hunk 3]
```diff
@@ -0,0 +1,141 @@
...
+import { u8aConcat, numberToU8a, u8aToBuffer } from '@polkadot/util';
+import { blake2AsHex } from '@polkadot/util-crypto';
+
+import { GraphQLModelsType } from '@subql/common/graphql/types';
+import { Entity } from '@subql/types';
+import MerkleTools from 'merkle-tools';
+import { OperationEntity, OperationType } from './types';
+
+export class StoreOperations {
+  private _stack: OperationEntity[] = [];
```
Comment (ianhe8x) [inline packages/node/src/indexer/StoreOperations.ts:13]: where is this used?

File: packages/node/src/indexer/poi.service.ts [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+// SPDX-License-Identifier: Apache-2.0
+
+import { OnApplicationShutdown } from '@nestjs/common';
+import { u8aConcat, numberToU8a, u8aToBuffer } from '@polkadot/util';
+import { blake2AsHex } from '@polkadot/util-crypto';
+import { SubqueryProject } from '../configure/project.model';
+
+const DEFAULT_PARENT_HASH = '0xabcd';
+
+export class PoiService implements OnApplicationShutdown {
```
Comment (ianhe8x) [inline packages/node/src/indexer/poi.service.ts:11]: is it stateless? it looks more like a utility

File: packages/node/src/indexer/store.service.ts [hunk 5]
```diff
@@ -17,8 +18,13 @@ import {
...
   smartTags,
 } from '../utils/sync-helper';
-
+import { MetadataFactory, MetadataRepo } from './entities/Metadata.entity';
+import { PoiFactory, PoiRepo, ProofOfIndex } from './entities/Poi.entity';
+import { PoiService } from './poi.service';
+import { StoreOperations } from './StoreOperations';
+import { OperationType } from './types';
 const logger = getLogger('store');
+const NULL_MERKEL_ROOT = '0x100';
```
Comment (ianhe8x) [inline packages/node/src/indexer/store.service.ts:27]: this is not valid, it need to be align to bytes. like `0x1000` or `0x0100`

File: packages/node/src/indexer/indexer.manager.ts [hunk 6]
```diff
@@ -53,6 +56,8 @@ export class IndexerManager {
     const tx = await this.sequelize.transaction();
     this.storeService.setTransaction(tx);
 
+    let PoiBlockHash: string;
```
Comment (ianhe8x) [inline packages/node/src/indexer/indexer.manager.ts:59]: lower case

File: packages/node/src/indexer/poi.service.ts (hunk 4 above)
Comment (ianhe8x) [reply packages/node/src/indexer/poi.service.ts:11]: you probably can define a PoiBlock class and define toHash() on it

File: packages/node/src/indexer/entities/Poi.entity.ts [hunk 7]
```diff
@@ -0,0 +1,60 @@
...
+  mmrRoot: string | Buffer;
+  projectId: string;
+}
+
+export type PoiRepo = typeof Model & {
+  new (values?: unknown, options?: BuildOptions): ProofOfIndex;
+};
+
+export function PoiFactory(sequelize: Sequelize, schema: string): PoiRepo {
+  return <PoiRepo>sequelize.define(
```
Comment (ianhe8x) [inline packages/node/src/indexer/entities/Poi.entity.ts:21]: don't forget to define indexes.
I think on `id` and `hash`

**Review by ianhe8x — CHANGES_REQUESTED** [review]

File: packages/node/package.json [hunk 8]
```diff
@@ -31,6 +31,9 @@
     "app-module-path": "^2.2.0",
     "dayjs": "^1.10.5",
     "lodash": "^4.17.21",
+    "merkle-mountain-range": "^2.0.0",
+    "merkle-tools": "^1.4.1",
+    "object-hash": "^2.2.0",
```
Comment (ianhe8x) [inline packages/node/package.json:36]: is this the lib you think can help with generate hash for object? I can't find it been used anywhere.

File: packages/node/src/indexer/StoreOperations.spec.ts [hunk 9]
```diff
@@ -74,6 +75,22 @@ describe('StoreOperations', () => {
           { name: 'field3', type: 'BigInt', isArray: false, nullable: true },
           { name: 'field4', type: 'Date', isArray: false, nullable: true },
           { name: 'field5', type: 'Boolean', isArray: false, nullable: true },
+          { name: 'field6', type: 'Food', isArray: false, nullable: true },
+        ],
+        indexes: [],
+      },
+      {
+        name: 'Food',
```
Comment (ianhe8x) [inline packages/node/src/indexer/StoreOperations.spec.ts:83]: is food a jsonField or entity?

File: packages/node/src/indexer/StoreOperations.ts [hunk 10]
```diff
@@ -24,87 +23,56 @@ export class StoreOperations {
     let operationBuffer: Uint8Array = new Uint8Array();
     //expect output: blake2AsHex(["id","1", "field1","12300000",...]) = "0xasdasd..."
     let dataBuffer: Uint8Array = new Uint8Array();
```
Comment (ianhe8x) [inline packages/node/src/indexer/StoreOperations.ts:25]: this is no needed anymore

File: packages/node/src/indexer/StoreOperations.ts [hunk 11]
```diff
@@ -24,87 +23,56 @@ export class StoreOperations {
...
           }
         }
       }
     }
+    dataBuffer = u8aConcat(dataBuffer, ...dataBufferArray);
     operationBuffer = u8aConcat(
       operationBuffer,
+      Buffer.from(operation.operation),
+      Buffer.from(operation.entityType),
       Buffer.from(blake2AsHex(dataBuffer)),
```
Comment (ianhe8x) [inline packages/node/src/indexer/StoreOperations.ts:73]: Can we skip hashing here? or there are other concerns?

File: packages/node/src/indexer/StoreOperations.ts [hunk 12]
```diff
@@ -24,87 +23,56 @@ export class StoreOperations {
...
-              );
+              dataBufferArray.push(Buffer.from(JSON.stringify(fieldValue)));
               break;
           }
         }
       }
     }
+    dataBuffer = u8aConcat(dataBuffer, ...dataBufferArray);
     operationBuffer = u8aConcat(
       operationBuffer,
```
Comment (ianhe8x) [inline packages/node/src/indexer/StoreOperations.ts:70]: operationBuffer was empty, so you can just change it to 
```
const operationBuffer = u8aConcat(
 Buffer.from(operation.operation),
       Buffer.from(operation.entityType),
       Buffer.from(dataBuffer),
)

```

File: packages/node/src/indexer/entities/Poi.entity.ts [hunk 13]
```diff
@@ -13,8 +13,10 @@ export interface ProofOfIndex {
   projectId: string;
 }
 
+export interface PoiModel extends Model<ProofOfIndex>, ProofOfIndex {}
+
 export type PoiRepo = typeof Model & {
-  new (values?: unknown, options?: BuildOptions): ProofOfIndex;
+  new (values?: unknown, options?: BuildOptions): PoiModel;
```
Comment (ianhe8x) [inline packages/node/src/indexer/entities/Poi.entity.ts:19]: I don't think PoiRepo will create PoiModel.

File: packages/node/src/indexer/entities/Poi.entity.ts [hunk 14]
```diff
@@ -37,7 +39,7 @@ export function PoiFactory(sequelize: Sequelize, schema: string): PoiRepo {
       },
       parentHash: {
         type: DataTypes.BLOB,
-        allowNull: true,
+        allowNull: false,
```
Comment (ianhe8x) [inline packages/node/src/indexer/entities/Poi.entity.ts:42]: first block doesn't have parentHash, are you planning to use `0x00` for the first block?

File: packages/node/src/indexer/PoiBlock.ts [hunk 15]
```diff
@@ -0,0 +1,55 @@
...
+    const poiBlock = new PoiBlock();
+    poiBlock.id = id;
+    poiBlock.chainBlockHash = chainBlockHash;
+    poiBlock.operationHashRoot = operationHashRoot;
+    poiBlock.parentHash = parentHash;
+    poiBlock.projectId = projectId;
+    return poiBlock;
+  }
+
+  get toHash(): string {
```
Comment (ianhe8x) [inline packages/node/src/indexer/PoiBlock.ts:35]: toHash is a method, if you use getter, you can just name it after `get hash()`

File: packages/node/src/indexer/poi.service.ts [hunk 16]
```diff
@@ -1,71 +1,62 @@
...
-      throw new Error('Poof of index: can not generate block hash');
+  async getLatestPoiBlockHash(schema?: string): Promise<string | Buffer> {
+    if (schema) {
+      this.poiRepo = PoiFactory(this.sequelize, schema);
+      const lastPoi = await this.poiRepo.findOne({
+        order: [['createdAt', 'DESC']],
+      });
+      if (lastPoi === null) {
+        this.latestPoiBlockHash = DEFAULT_PARENT_HASH;
+      } else if (lastPoi !== null && lastPoi.hash) {
```
Comment (ianhe8x) [inline packages/node/src/indexer/poi.service.ts]: `poiRepo.findOne()` doesn't suppose to return `PoiBlock` object. so lastPoi.hash won't work.

File: packages/node/src/indexer/PoiBlock.ts [hunk 17]
```diff
@@ -0,0 +1,55 @@
+// Copyright 2020-2021 OnFinality Limited authors & contributors
+// SPDX-License-Identifier: Apache-2.0
+// eslint-disable-next-line header/header
+import { u8aConcat, numberToU8a, u8aToBuffer } from '@polkadot/util';
+import { blake2AsHex } from '@polkadot/util-crypto';
+import { SubqueryProject } from '../configure/project.model';
+
+const DEFAULT_PARENT_HASH = '0xabcd';
```
Comment (ianhe8x) [inline packages/node/src/indexer/PoiBlock.ts:8]: Why is this the default parent hash?

File: packages/node/src/indexer/poi.service.ts [hunk 18]
```diff
@@ -1,71 +1,62 @@
...
+import { SubqueryRepo } from '../entities';
+import {
+  PoiFactory,
+  PoiRepo,
+  ProofOfIndex,
+  PoiModel,
+} from './entities/Poi.entity';
+import { PoiBlock } from './PoiBlock';
 
 const DEFAULT_PARENT_HASH = '0xabcd';
```
Comment (ianhe8x) [inline packages/node/src/indexer/poi.service.ts:10]: also here

File: packages/node/src/indexer/poi.service.ts [hunk 19]
```diff
@@ -1,71 +1,62 @@
...
-        this.latestParentHash ? this.latestParentHash : DEFAULT_PARENT_HASH,
-      ),
-    );
-    return blake2AsHex(buffer);
-  }
-
-  getLatestBlockHash(): string {
-    //TODO, try to get latest hash from database
-    return this.latestParentHash ? this.latestParentHash : DEFAULT_PARENT_HASH;
+    return this.latestPoiBlockHash
```
Comment (ianhe8x) [inline packages/node/src/indexer/poi.service.ts]: I don't follow the logic here

**Review by ianhe8x — CHANGES_REQUESTED** [review]

File: packages/node/src/indexer/poi.service.ts [hunk 20]
```diff
@@ -36,24 +27,69 @@ export class PoiService implements OnApplicationShutdown {
...
+      return null;
+    } else if (lastPoi !== null && lastPoi.hash) {
+      return lastPoi.hash;
+    } else {
+      throw new Error(`Poi found but can not get latest hash`);
+    }
+  }
+
+  async fetchBlockOffsetFromDb(schema: string): Promise<number | null> {
+    this.metadataRepo = MetadataFactory(this.sequelize, schema);
```
Comment (ianhe8x) [inline packages/node/src/indexer/poi.service.ts:56]: this.metadataRepo initialization should only happen once.
in the constructor() or init()

File: packages/node/src/indexer/poi.service.ts [hunk 21]
```diff
@@ -36,24 +27,69 @@ export class PoiService implements OnApplicationShutdown {
...
+      : DEFAULT_PARENT_HASH;
+    this.blockOffset = await this.fetchBlockOffsetFromDb(schema);
+  }
+
+  async fetchLatestPoiBlockHashFromDb(
+    schema: string,
+  ): Promise<string | Buffer | null> {
+    this.poiRepo = PoiFactory(this.sequelize, schema);
+    const lastPoi = await this.poiRepo.findOne({
+      order: [['createdAt', 'DESC']],
```
Comment (ianhe8x) [inline packages/node/src/indexer/poi.service.ts:44]: don't sort, it is too expensive and slow. You shall know the last processed height, so you can query via the height.

File: packages/node/src/indexer/poi.service.ts [hunk 22]
```diff
@@ -36,24 +27,69 @@ export class PoiService implements OnApplicationShutdown {
...
+    const latestPoiBlockHash = await this.fetchLatestPoiBlockHashFromDb(schema);
+    this.latestPoiBlockHash = latestPoiBlockHash
+      ? latestPoiBlockHash
+      : DEFAULT_PARENT_HASH;
+    this.blockOffset = await this.fetchBlockOffsetFromDb(schema);
+  }
+
+  async fetchLatestPoiBlockHashFromDb(
+    schema: string,
+  ): Promise<string | Buffer | null> {
```
Comment (ianhe8x) [inline packages/node/src/indexer/poi.service.ts:41]: pls tidy up return types.

File: packages/node/src/indexer/poi.service.ts [hunk 23]
```diff
@@ -36,24 +27,69 @@ export class PoiService implements OnApplicationShutdown {
...
-        this.latestPoiBlockHash = DEFAULT_PARENT_HASH;
-      } else if (lastPoi !== null && lastPoi.hash) {
-        this.latestPoiBlockHash = lastPoi.hash;
+  async init(schema: string): Promise<void> {
+    this.schema = schema;
+    const latestPoiBlockHash = await this.fetchLatestPoiBlockHashFromDb(schema);
+    this.latestPoiBlockHash = latestPoiBlockHash
+      ? latestPoiBlockHash
+      : DEFAULT_PARENT_HASH;
+    this.blockOffset = await this.fetchBlockOffsetFromDb(schema);
```
Comment (ianhe8x) [inline packages/node/src/indexer/poi.service.ts:36]: parallelize fetchLatestPoiBlockHashFromDb and fetchBlockOffsetFromDb

File: packages/node/src/indexer/poi.service.ts [hunk 24]
```diff
@@ -36,24 +27,69 @@ export class PoiService implements OnApplicationShutdown {
...
+    } else {
+      throw new Error(`Poi found but can not get latest hash`);
+    }
+  }
+
+  async fetchBlockOffsetFromDb(schema: string): Promise<number | null> {
+    this.metadataRepo = MetadataFactory(this.sequelize, schema);
+    const blockOffset = await this.metadataRepo.findOne({
+      where: { key: 'blockOffset' },
+      order: [['createdAt', 'DESC']],
```
Comment (ianhe8x) [inline packages/node/src/indexer/poi.service.ts:59]: no need to sort

File: packages/node/src/indexer/poi.service.ts [hunk 25]
```diff
@@ -36,24 +27,69 @@ export class PoiService implements OnApplicationShutdown {
...
+    });
+    if (blockOffset === null) {
```
Comment (ianhe8x) [inline packages/node/src/indexer/poi.service.ts:61]: when not found, are you sure it will be null not undefined?

File: packages/node/src/indexer/poi.service.ts [hunk 26]
```diff
@@ -36,24 +27,69 @@ export class PoiService implements OnApplicationShutdown {
...
+          schema ? schema : this.schema,
+        );
+      }
+    }
+    return this.blockOffset;
+  }
+
+  //allow pass schema here , can be re-used for future validation
+  async getLatestPoiBlockHash(
+    schema?: string,
```
Comment (ianhe8x) [inline packages/node/src/indexer/poi.service.ts:80]: In what cases, we might need to pass a schema different from this.schema?

File: packages/node/src/indexer/poi.service.ts [hunk 27]
```diff
@@ -36,24 +27,69 @@ export class PoiService implements OnApplicationShutdown {
...
+  ): Promise<string | Buffer | null> {
+    if (!this.latestPoiBlockHash) {
+      if (this.schema || schema) {
+        this.latestPoiBlockHash = await this.fetchLatestPoiBlockHashFromDb(
+          schema ? schema : this.schema,
+        );
         return this.latestPoiBlockHash;
```
Comment (ianhe8x) [inline packages/node/src/indexer/poi.service.ts:87]: check if the return from db is null/undefined then return DEFAULT_PARENT_HASH

File: packages/node/src/indexer/poi.service.ts [hunk 28]
```diff
@@ -36,24 +27,69 @@ export class PoiService implements OnApplicationShutdown {
...
       } else {
-        throw new Error(`Poi found but can not get latest hash`);
+        throw new Error(`Failed to fetch latest Poi`);
       }
     }
-    return this.latestPoiBlockHash
-      ? this.latestPoiBlockHash
-      : DEFAULT_PARENT_HASH;
+    return this.latestPoiBlockHash;
```
Comment (ianhe8x) [inline packages/node/src/indexer/poi.service.ts:92]: In what cases it will hit this line?

**Review by ianhe8x — CHANGES_REQUESTED** [review]

**Review by ianhe8x — APPROVED** [review]

**Comment by ianhe8x** [comment]
I'm ok with it, solve the conflicts and you are ready to go.

File: packages/node/src/indexer/StoreOperations.ts [hunk 29]
```diff
@@ -18,7 +18,10 @@ export class StoreOperations {
 
   private operationEntityToUint8Array(operation: OperationEntity): Uint8Array {
     const dataBufferArray: Uint8Array[] = [];
-    if (operation.operation === OperationType.Remove) {
+    if (
+      operation.operation === OperationType.Remove &&
+      isString(operation.data)
```
Comment (ianhe8x) [inline packages/node/src/indexer/StoreOperations.ts:23]: In which cases data is not string? If it isn't, shall we throw error?

**Review by ianhe8x — APPROVED** [review]
