### PR TITLE
Fix/abi codegen

### LINKED ISSUE #1768: Ethereum ABI codegen doesn't include template datasources

### PR DESCRIPTION
**Pull request by bz888**
# Description
Fixes for ABI codegen to include template datasources and customDatasources

Fixes #1768 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have tested locally
- [x] I have performed a self review of my changes
- [x] Linked to any relevant issues
- [x] I have added tests relevant to my changes
- [x] My code is up to date with the base branch
- [ ] I have updated relevant changelogs. [We suggest using chan](https://github.com/geut/chan/tree/main/packages/chan)

### CODE REVIEW

File: packages/cli/src/controller/codegen-controller.ts [hunk 1]
```diff
@@ -370,13 +374,45 @@ export async function codegen(projectPath: string, fileName?: string): Promise<v
...
+    'runner',
+    'description',
+    'repository',
+    'schema',
+    'network',
+  ];
+  const dsKeys = ['assets', 'kind', 'processor'];
+  // I need to determine if it is a datasource
+
+  const customDatasource = Object.keys(plainManifest)
```
Comment (stwiname) [inline packages/cli/src/controller/codegen-controller.ts:393]: Why do we determine if its a custom ds?

**Review by stwiname — APPROVED** [review]
